name: cdi
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python=3.8.18
  - pip
  - cudatoolkit
  - pytorch=2.2
  - pytorch-cuda
  - torchvision=0.17.0
  - numpy
  - scipy=1.10.1
  - scikit-learn=1.3.2
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio
    - imageio-ffmpeg
    - pytorch-lightning==1.5
    - omegaconf
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.31
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - timm
    - diffusers
    - accelerate
    - absl-py 
    - ml_collections 
    - einops 
    - ftfy==6.1.1
    - hydra-core==1.3.2
    - matplotlib
    - gdown
    - kornia
    - seaborn
    - absl-py
    - pycocotools
